# Generated by Django 4.0.2 on 2022-02-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='address',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
